// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(overend_coreFFI)
import overend_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_overend_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_overend_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Main engine for OVEREND document processing
 */
public protocol OverendEngineProtocol : AnyObject {
    
    /**
     * Compile Typst source to PDF
     *
     * # Arguments
     * * `source` - Typst markup source code
     * * `font_data` - Optional font data (e.g., Noto Serif TC)
     *
     * # Returns
     * PDF bytes on success, TypstError on failure
     */
    func compileTypst(source: String, fontData: Data?) throws  -> Data
    
    /**
     * Format citations using a specific style (simplified)
     *
     * For full CSL support, use Swift-side CitationService.
     *
     * # Arguments
     * * `bibtex_content` - BibTeX source
     * * `cite_keys` - List of citation keys to format
     * * `style` - Citation style to use
     *
     * # Returns
     * Formatted citation string
     */
    func formatCitation(bibtexContent: String, citeKeys: [String], style: RustCitationStyle) throws  -> String
    
    /**
     * Generate a formatted bibliography list (simplified)
     *
     * For full CSL support, use Swift-side CitationService.
     *
     * # Arguments
     * * `bibtex_content` - BibTeX source
     * * `style` - Citation style to use
     *
     * # Returns
     * List of formatted bibliography entries
     */
    func generateBibliography(bibtexContent: String, style: RustCitationStyle) throws  -> [String]
    
    /**
     * Hello world test function
     */
    func helloWorld()  -> String
    
    /**
     * Parse BibTeX content into structured entries
     *
     * # Arguments
     * * `content` - BibTeX file content
     *
     * # Returns
     * List of BibEntry records
     */
    func parseBibtex(content: String) throws  -> [BibEntry]
    
    func renderPdf(source: String)  -> String
    
}

/**
 * Main engine for OVEREND document processing
 */
open class OverendEngine:
    OverendEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_overend_core_fn_clone_overendengine(self.pointer, $0) }
    }
    /**
     * Create a new OverendEngine instance
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_overend_core_fn_constructor_overendengine_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_overend_core_fn_free_overendengine(pointer, $0) }
    }

    

    
    /**
     * Compile Typst source to PDF
     *
     * # Arguments
     * * `source` - Typst markup source code
     * * `font_data` - Optional font data (e.g., Noto Serif TC)
     *
     * # Returns
     * PDF bytes on success, TypstError on failure
     */
open func compileTypst(source: String, fontData: Data?)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeTypstError.lift) {
    uniffi_overend_core_fn_method_overendengine_compile_typst(self.uniffiClonePointer(),
        FfiConverterString.lower(source),
        FfiConverterOptionData.lower(fontData),$0
    )
})
}
    
    /**
     * Format citations using a specific style (simplified)
     *
     * For full CSL support, use Swift-side CitationService.
     *
     * # Arguments
     * * `bibtex_content` - BibTeX source
     * * `cite_keys` - List of citation keys to format
     * * `style` - Citation style to use
     *
     * # Returns
     * Formatted citation string
     */
open func formatCitation(bibtexContent: String, citeKeys: [String], style: RustCitationStyle)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBibliographyError.lift) {
    uniffi_overend_core_fn_method_overendengine_format_citation(self.uniffiClonePointer(),
        FfiConverterString.lower(bibtexContent),
        FfiConverterSequenceString.lower(citeKeys),
        FfiConverterTypeRustCitationStyle.lower(style),$0
    )
})
}
    
    /**
     * Generate a formatted bibliography list (simplified)
     *
     * For full CSL support, use Swift-side CitationService.
     *
     * # Arguments
     * * `bibtex_content` - BibTeX source
     * * `style` - Citation style to use
     *
     * # Returns
     * List of formatted bibliography entries
     */
open func generateBibliography(bibtexContent: String, style: RustCitationStyle)throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeBibliographyError.lift) {
    uniffi_overend_core_fn_method_overendengine_generate_bibliography(self.uniffiClonePointer(),
        FfiConverterString.lower(bibtexContent),
        FfiConverterTypeRustCitationStyle.lower(style),$0
    )
})
}
    
    /**
     * Hello world test function
     */
open func helloWorld() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_overend_core_fn_method_overendengine_hello_world(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Parse BibTeX content into structured entries
     *
     * # Arguments
     * * `content` - BibTeX file content
     *
     * # Returns
     * List of BibEntry records
     */
open func parseBibtex(content: String)throws  -> [BibEntry] {
    return try  FfiConverterSequenceTypeBibEntry.lift(try rustCallWithError(FfiConverterTypeBibliographyError.lift) {
    uniffi_overend_core_fn_method_overendengine_parse_bibtex(self.uniffiClonePointer(),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func renderPdf(source: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_overend_core_fn_method_overendengine_render_pdf(self.uniffiClonePointer(),
        FfiConverterString.lower(source),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOverendEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OverendEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OverendEngine {
        return OverendEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OverendEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OverendEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OverendEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOverendEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> OverendEngine {
    return try FfiConverterTypeOverendEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOverendEngine_lower(_ value: OverendEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOverendEngine.lower(value)
}


/**
 * A bibliography entry exported to Swift
 */
public struct BibEntry {
    public var key: String
    public var title: String?
    public var authors: [String]
    public var year: String?
    public var entryType: String
    public var journal: String?
    public var volume: String?
    public var pages: String?
    public var doi: String?
    public var url: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, title: String?, authors: [String], year: String?, entryType: String, journal: String?, volume: String?, pages: String?, doi: String?, url: String?) {
        self.key = key
        self.title = title
        self.authors = authors
        self.year = year
        self.entryType = entryType
        self.journal = journal
        self.volume = volume
        self.pages = pages
        self.doi = doi
        self.url = url
    }
}



extension BibEntry: Equatable, Hashable {
    public static func ==(lhs: BibEntry, rhs: BibEntry) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.authors != rhs.authors {
            return false
        }
        if lhs.year != rhs.year {
            return false
        }
        if lhs.entryType != rhs.entryType {
            return false
        }
        if lhs.journal != rhs.journal {
            return false
        }
        if lhs.volume != rhs.volume {
            return false
        }
        if lhs.pages != rhs.pages {
            return false
        }
        if lhs.doi != rhs.doi {
            return false
        }
        if lhs.url != rhs.url {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(title)
        hasher.combine(authors)
        hasher.combine(year)
        hasher.combine(entryType)
        hasher.combine(journal)
        hasher.combine(volume)
        hasher.combine(pages)
        hasher.combine(doi)
        hasher.combine(url)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBibEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BibEntry {
        return
            try BibEntry(
                key: FfiConverterString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                authors: FfiConverterSequenceString.read(from: &buf), 
                year: FfiConverterOptionString.read(from: &buf), 
                entryType: FfiConverterString.read(from: &buf), 
                journal: FfiConverterOptionString.read(from: &buf), 
                volume: FfiConverterOptionString.read(from: &buf), 
                pages: FfiConverterOptionString.read(from: &buf), 
                doi: FfiConverterOptionString.read(from: &buf), 
                url: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: BibEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterSequenceString.write(value.authors, into: &buf)
        FfiConverterOptionString.write(value.year, into: &buf)
        FfiConverterString.write(value.entryType, into: &buf)
        FfiConverterOptionString.write(value.journal, into: &buf)
        FfiConverterOptionString.write(value.volume, into: &buf)
        FfiConverterOptionString.write(value.pages, into: &buf)
        FfiConverterOptionString.write(value.doi, into: &buf)
        FfiConverterOptionString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBibEntry_lift(_ buf: RustBuffer) throws -> BibEntry {
    return try FfiConverterTypeBibEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBibEntry_lower(_ value: BibEntry) -> RustBuffer {
    return FfiConverterTypeBibEntry.lower(value)
}


/**
 * Errors that can occur during bibliography processing
 */
public enum BibliographyError {

    
    
    case ParseError(message: String
    )
    case StyleError(message: String
    )
    case FormatError(message: String
    )
    case EntryNotFound(key: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBibliographyError: FfiConverterRustBuffer {
    typealias SwiftType = BibliographyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BibliographyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .StyleError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .FormatError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .EntryNotFound(
            key: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BibliographyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .StyleError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .FormatError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .EntryNotFound(key):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(key, into: &buf)
            
        }
    }
}


extension BibliographyError: Equatable, Hashable {}

extension BibliographyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Supported citation styles
 */

public enum RustCitationStyle {
    
    case apa
    case chicagoAuthorDate
    case ieee
    case mla
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustCitationStyle: FfiConverterRustBuffer {
    typealias SwiftType = RustCitationStyle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustCitationStyle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .apa
        
        case 2: return .chicagoAuthorDate
        
        case 3: return .ieee
        
        case 4: return .mla
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RustCitationStyle, into buf: inout [UInt8]) {
        switch value {
        
        
        case .apa:
            writeInt(&buf, Int32(1))
        
        
        case .chicagoAuthorDate:
            writeInt(&buf, Int32(2))
        
        
        case .ieee:
            writeInt(&buf, Int32(3))
        
        
        case .mla:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustCitationStyle_lift(_ buf: RustBuffer) throws -> RustCitationStyle {
    return try FfiConverterTypeRustCitationStyle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustCitationStyle_lower(_ value: RustCitationStyle) -> RustBuffer {
    return FfiConverterTypeRustCitationStyle.lower(value)
}



extension RustCitationStyle: Equatable, Hashable {}




/**
 * Errors that can occur during Typst compilation
 */
public enum TypstError {

    
    
    case CompilationFailed(message: String
    )
    case SourceError(message: String
    )
    case FontError(message: String
    )
    case PdfError(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTypstError: FfiConverterRustBuffer {
    typealias SwiftType = TypstError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TypstError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .CompilationFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .SourceError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .FontError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .PdfError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TypstError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .CompilationFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SourceError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .FontError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .PdfError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension TypstError: Equatable, Hashable {}

extension TypstError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBibEntry: FfiConverterRustBuffer {
    typealias SwiftType = [BibEntry]

    public static func write(_ value: [BibEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBibEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BibEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [BibEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBibEntry.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_overend_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_compile_typst() != 52748) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_format_citation() != 52069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_generate_bibliography() != 55899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_hello_world() != 53098) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_parse_bibtex() != 22501) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_method_overendengine_render_pdf() != 10950) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_overend_core_checksum_constructor_overendengine_new() != 57847) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all